module.exports = {
  info: {
    title: 'KYCDOC API',
    version: '1.0.0',
    description: 'KYCDOC API  with autogenerated swagger doc'
  },
  components: {
    securitySchemes: {
      type: 'http',
      scheme: 'basic'
    }
  },
  basePath: '/'
};
