module.exports = {
  info: {
    title: 'SWAGGER API',
    version: '1.0.0',
    description: 'SWAGGER API  with autogenerated swagger doc'
  },
  components: {
    securitySchemes: {
      type: 'http',
      scheme: 'basic'
    }
  },
  basePath: '/api/'
};
